DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Employee;

CREATE TABLE Department (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    dept_name VARCHAR(20) NOT NULL UNIQUE
);
CREATE TABLE Role (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30),
    salary DECIMAL,
    department_id INTEGER NOT NULL
);
CREATE TABLE Employee (
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    role_id INTEGER NOT NULL,
    manager_id INTEGER
);